### PR TITLE
Make WP_Less_Is_More_Page_Walker shorter

### PR DESCRIPTION
**Pull request by szepeviktor**
-15 lines
What do you think?

### CODE REVIEW

**Review by mrpauloen — APPROVED** [review]
ok.

**Comment by szepeviktor** [comment]
How great PR-s I used to send in 2020!

**Comment by mrpauloen** [comment]
> How great PR-s I used to send in 2020!

What do you mean by that?

**Comment by szepeviktor** [comment]
> What do you mean by that?

Nowadays I do not send that good PR-s.

**Pull request merged**
